# Generated by Django 6.1.2 on 2026-10-09 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, help_text="Or 'Traditionally attributed to ...'", max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('tradition', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(help_text='Two or three sentences on why it is worth reading.')),
                ('suggested_pace', models.CharField(blank=True, help_text="e.g. 'Six sessions, about 4 books each'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translator', models.CharField(max_length=200)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=17, verbose_name='ISBN')),
                ('cover', models.ImageField(blank=True, help_text='Use your own photo of your copy.', upload_to='editions/')),
                ('cover_alt', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Why choose it: introduction, notes, readability.')),
                ('is_group_edition', models.BooleanField(default=False, help_text='The edition the group uses.')),
                ('public_domain', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True, help_text='Publisher page or a library catalog entry.')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='frontmatter.text')),
            ],
            options={
                'ordering': ['-is_group_edition', 'translator'],
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('start_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frontmatter.text')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('venue_address', models.CharField(blank=True, max_length=300)),
                ('passage', models.CharField(help_text="e.g. 'Analects 1-2'", max_length=200)),
                ('assignment_for_next', models.CharField(blank=True, max_length=200)),
                ('published', models.BooleanField(default=False)),
                ('headcount', models.PositiveIntegerField(blank=True, null=True)),
                ('opening_question', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('unresolved', models.TextField(blank=True, help_text='One open question per line.')),
                ('facilitator_note', models.TextField(blank=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='frontmatter.cycle')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('cycle', 'number')},
            },
        ),
    ]
